package mnj.ont.model.lov.views;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 01 13:09:48 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StyleRefLovRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        StyleRef {
            public Object get(StyleRefLovRowImpl obj) {
                return obj.getStyleRef();
            }

            public void put(StyleRefLovRowImpl obj, Object value) {
                obj.setStyleRef((String)value);
            }
        }
        ,
        FromSize {
            public Object get(StyleRefLovRowImpl obj) {
                return obj.getFromSize();
            }

            public void put(StyleRefLovRowImpl obj, Object value) {
                obj.setFromSize((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(StyleRefLovRowImpl object);

        public abstract void put(StyleRefLovRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int STYLEREF = AttributesEnum.StyleRef.index();
    public static final int FROMSIZE = AttributesEnum.FromSize.index();

    /**
     * This is the default constructor (do not remove).
     */
    public StyleRefLovRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute StyleRef.
     * @return the StyleRef
     */
    public String getStyleRef() {
        return (String) getAttributeInternal(STYLEREF);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StyleRef.
     * @param value value to set the  StyleRef
     */
    public void setStyleRef(String value) {
        setAttributeInternal(STYLEREF, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FromSize.
     * @return the FromSize
     */
    public String getFromSize() {
        return (String) getAttributeInternal(FROMSIZE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FromSize.
     * @param value value to set the  FromSize
     */
    public void setFromSize(String value) {
        setAttributeInternal(FROMSIZE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
