package mnj.ont.model.services.client;

import mnj.ont.model.services.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 03 11:26:05 BDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }


    public String callSplitSizes() {
        Object _ret = this.riInvokeExportedMethod(this,"callSplitSizes",null,null);
        return (String)_ret;
    }

    public String callMatrix() {
        Object _ret = this.riInvokeExportedMethod(this,"callMatrix",null,null);
        return (String)_ret;
    }

    public String uploadDCPOs() {
        Object _ret = this.riInvokeExportedMethod(this,"uploadDCPOs",null,null);
        return (String)_ret;
    }

    public void lineValidation() {
        Object _ret = this.riInvokeExportedMethod(this,"lineValidation",null,null);
        return;
    }

    public void setSessionValues(String orgId, String userId, String respId,
                                 String respAppl) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setSessionValues",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {orgId, userId, respId, respAppl});
        return;
    }
}
