package mnj.ont.model.entities;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jul 23 11:50:03 BDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustMnjOntSizUploadTempImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        TempId {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getTempId();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setTempId((Number)value);
            }
        }
        ,
        LineId {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getLineId();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        SizeDetailId {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getSizeDetailId();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setSizeDetailId((Number)value);
            }
        }
        ,
        Stn {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getStn();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setStn((String)value);
            }
        }
        ,
        SalesOrderId {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getSalesOrderId();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setSalesOrderId((Number)value);
            }
        }
        ,
        InventoryItemId {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getInventoryItemId();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setInventoryItemId((Number)value);
            }
        }
        ,
        Bpo {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getBpo();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setBpo((String)value);
            }
        }
        ,
        Color {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getColor();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setColor((String)value);
            }
        }
        ,
        Country {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getCountry();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setCountry((String)value);
            }
        }
        ,
        DcpoCode {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getDcpoCode();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setDcpoCode((String)value);
            }
        }
        ,
        TotalQty {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getTotalQty();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setTotalQty((Number)value);
            }
        }
        ,
        DeliveryDate {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getDeliveryDate();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setDeliveryDate((String)value);
            }
        }
        ,
        DeliveryTerm {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getDeliveryTerm();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setDeliveryTerm((String)value);
            }
        }
        ,
        ShipMode {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getShipMode();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setShipMode((String)value);
            }
        }
        ,
        SizeInseam {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getSizeInseam();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setSizeInseam((String)value);
            }
        }
        ,
        SizeQty {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getSizeQty();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setSizeQty((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getAttribute1();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getAttribute2();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getAttribute3();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getAttribute4();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getAttribute6();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getAttribute5();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getAttribute7();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getAttribute8();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getAttribute9();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getAttribute10();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        UploadFlag {
            public Object get(CustMnjOntSizUploadTempImpl obj) {
                return obj.getUploadFlag();
            }

            public void put(CustMnjOntSizUploadTempImpl obj, Object value) {
                obj.setUploadFlag((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(CustMnjOntSizUploadTempImpl object);

        public abstract void put(CustMnjOntSizUploadTempImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int TEMPID = AttributesEnum.TempId.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int SIZEDETAILID = AttributesEnum.SizeDetailId.index();
    public static final int STN = AttributesEnum.Stn.index();
    public static final int SALESORDERID = AttributesEnum.SalesOrderId.index();
    public static final int INVENTORYITEMID = AttributesEnum.InventoryItemId.index();
    public static final int BPO = AttributesEnum.Bpo.index();
    public static final int COLOR = AttributesEnum.Color.index();
    public static final int COUNTRY = AttributesEnum.Country.index();
    public static final int DCPOCODE = AttributesEnum.DcpoCode.index();
    public static final int TOTALQTY = AttributesEnum.TotalQty.index();
    public static final int DELIVERYDATE = AttributesEnum.DeliveryDate.index();
    public static final int DELIVERYTERM = AttributesEnum.DeliveryTerm.index();
    public static final int SHIPMODE = AttributesEnum.ShipMode.index();
    public static final int SIZEINSEAM = AttributesEnum.SizeInseam.index();
    public static final int SIZEQTY = AttributesEnum.SizeQty.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int UPLOADFLAG = AttributesEnum.UploadFlag.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CustMnjOntSizUploadTempImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.ont.model.entities.CustMnjOntSizUploadTemp");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for TempId, using the alias name TempId.
     * @return the TempId
     */
    public Number getTempId() {
        return (Number)getAttributeInternal(TEMPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TempId.
     * @param value value to set the TempId
     */
    public void setTempId(Number value) {
        setAttributeInternal(TEMPID, value);
    }

    /**
     * Gets the attribute value for LineId, using the alias name LineId.
     * @return the LineId
     */
    public Number getLineId() {
        return (Number)getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineId.
     * @param value value to set the LineId
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for SizeDetailId, using the alias name SizeDetailId.
     * @return the SizeDetailId
     */
    public Number getSizeDetailId() {
        return (Number)getAttributeInternal(SIZEDETAILID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizeDetailId.
     * @param value value to set the SizeDetailId
     */
    public void setSizeDetailId(Number value) {
        setAttributeInternal(SIZEDETAILID, value);
    }

    /**
     * Gets the attribute value for Stn, using the alias name Stn.
     * @return the Stn
     */
    public String getStn() {
        return (String)getAttributeInternal(STN);
    }

    /**
     * Sets <code>value</code> as the attribute value for Stn.
     * @param value value to set the Stn
     */
    public void setStn(String value) {
        setAttributeInternal(STN, value);
    }

    /**
     * Gets the attribute value for SalesOrderId, using the alias name SalesOrderId.
     * @return the SalesOrderId
     */
    public Number getSalesOrderId() {
        return (Number)getAttributeInternal(SALESORDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesOrderId.
     * @param value value to set the SalesOrderId
     */
    public void setSalesOrderId(Number value) {
        setAttributeInternal(SALESORDERID, value);
    }

    /**
     * Gets the attribute value for InventoryItemId, using the alias name InventoryItemId.
     * @return the InventoryItemId
     */
    public Number getInventoryItemId() {
        return (Number)getAttributeInternal(INVENTORYITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InventoryItemId.
     * @param value value to set the InventoryItemId
     */
    public void setInventoryItemId(Number value) {
        setAttributeInternal(INVENTORYITEMID, value);
    }

    /**
     * Gets the attribute value for Bpo, using the alias name Bpo.
     * @return the Bpo
     */
    public String getBpo() {
        return (String)getAttributeInternal(BPO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Bpo.
     * @param value value to set the Bpo
     */
    public void setBpo(String value) {
        setAttributeInternal(BPO, value);
    }

    /**
     * Gets the attribute value for Color, using the alias name Color.
     * @return the Color
     */
    public String getColor() {
        return (String)getAttributeInternal(COLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Color.
     * @param value value to set the Color
     */
    public void setColor(String value) {
        setAttributeInternal(COLOR, value);
    }

    /**
     * Gets the attribute value for Country, using the alias name Country.
     * @return the Country
     */
    public String getCountry() {
        return (String)getAttributeInternal(COUNTRY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Country.
     * @param value value to set the Country
     */
    public void setCountry(String value) {
        setAttributeInternal(COUNTRY, value);
    }

    /**
     * Gets the attribute value for DcpoCode, using the alias name DcpoCode.
     * @return the DcpoCode
     */
    public String getDcpoCode() {
        return (String)getAttributeInternal(DCPOCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DcpoCode.
     * @param value value to set the DcpoCode
     */
    public void setDcpoCode(String value) {
        setAttributeInternal(DCPOCODE, value);
    }

    /**
     * Gets the attribute value for TotalQty, using the alias name TotalQty.
     * @return the TotalQty
     */
    public Number getTotalQty() {
        return (Number)getAttributeInternal(TOTALQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalQty.
     * @param value value to set the TotalQty
     */
    public void setTotalQty(Number value) {
        setAttributeInternal(TOTALQTY, value);
    }

    /**
     * Gets the attribute value for DeliveryDate, using the alias name DeliveryDate.
     * @return the DeliveryDate
     */
    public String getDeliveryDate() {
        return (String)getAttributeInternal(DELIVERYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliveryDate.
     * @param value value to set the DeliveryDate
     */
    public void setDeliveryDate(String value) {
        setAttributeInternal(DELIVERYDATE, value);
    }

    /**
     * Gets the attribute value for DeliveryTerm, using the alias name DeliveryTerm.
     * @return the DeliveryTerm
     */
    public String getDeliveryTerm() {
        return (String)getAttributeInternal(DELIVERYTERM);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliveryTerm.
     * @param value value to set the DeliveryTerm
     */
    public void setDeliveryTerm(String value) {
        setAttributeInternal(DELIVERYTERM, value);
    }

    /**
     * Gets the attribute value for ShipMode, using the alias name ShipMode.
     * @return the ShipMode
     */
    public String getShipMode() {
        return (String)getAttributeInternal(SHIPMODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipMode.
     * @param value value to set the ShipMode
     */
    public void setShipMode(String value) {
        setAttributeInternal(SHIPMODE, value);
    }

    /**
     * Gets the attribute value for SizeInseam, using the alias name SizeInseam.
     * @return the SizeInseam
     */
    public String getSizeInseam() {
        return (String)getAttributeInternal(SIZEINSEAM);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizeInseam.
     * @param value value to set the SizeInseam
     */
    public void setSizeInseam(String value) {
        setAttributeInternal(SIZEINSEAM, value);
    }

    /**
     * Gets the attribute value for SizeQty, using the alias name SizeQty.
     * @return the SizeQty
     */
    public Number getSizeQty() {
        return (Number)getAttributeInternal(SIZEQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizeQty.
     * @param value value to set the SizeQty
     */
    public void setSizeQty(Number value) {
        setAttributeInternal(SIZEQTY, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for UploadFlag, using the alias name UploadFlag.
     * @return the UploadFlag
     */
    public String getUploadFlag() {
        return (String)getAttributeInternal(UPLOADFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for UploadFlag.
     * @param value value to set the UploadFlag
     */
    public void setUploadFlag(String value) {
        setAttributeInternal(UPLOADFLAG, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @param tempId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number tempId) {
        return new Key(new Object[]{tempId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("CUST_MNJ_SIZ_UPLOAD_TEMP_SEQ",getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setTempId(sVal);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}
