package mnj.ont.model.entities;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Feb 07 16:48:31 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustMnjOntSoObinslineDetailImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        SoObinslineHId {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getSoObinslineHId();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setSoObinslineHId((Number)value);
            }
        }
        ,
        SalesOrderId {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getSalesOrderId();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setSalesOrderId((Number)value);
            }
        }
        ,
        SolineId {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getSolineId();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setSolineId((Number)value);
            }
        }
        ,
        SoObinslineId {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getSoObinslineId();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setSoObinslineId((Number)value);
            }
        }
        ,
        ItemCode {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getItemCode();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setItemCode((String)value);
            }
        }
        ,
        SoObno {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getSoObno();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setSoObno((String)value);
            }
        }
        ,
        SizeGroupId {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getSizeGroupId();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setSizeGroupId((String)value);
            }
        }
        ,
        InseamId {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getInseamId();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setInseamId((String)value);
            }
        }
        ,
        TotalRatio {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getTotalRatio();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setTotalRatio((Number)value);
            }
        }
        ,
        InseamQty {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getInseamQty();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setInseamQty((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getCreationDate();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        InventoryItemId {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getInventoryItemId();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setInventoryItemId((Number)value);
            }
        }
        ,
        Obrefno {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getObrefno();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setObrefno((String)value);
            }
        }
        ,
        LegacyId {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getLegacyId();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setLegacyId((String)value);
            }
        }
        ,
        PackType {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getPackType();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setPackType((String)value);
            }
        }
        ,
        Uom {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getUom();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setUom((String)value);
            }
        }
        ,
        OrgId {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getOrgId();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        LineNo {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getLineNo();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setLineNo((Number)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getAttribute1();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getAttribute2();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getAttribute3();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getAttribute4();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getAttribute5();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getAttribute6();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getAttribute7();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getAttribute8();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getAttribute9();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getAttribute10();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getAttribute11();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getAttribute12();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getAttribute13();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getAttribute14();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getAttribute15();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        SizeValue {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getSizeValue();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setSizeValue((Number)value);
            }
        }
        ,
        SizeQty {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getSizeQty();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setSizeQty((Number)value);
            }
        }
        ,
        SizeKey {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getSizeKey();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setSizeKey((String)value);
            }
        }
        ,
        InseamSizeConcat {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getInseamSizeConcat();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setInseamSizeConcat((String)value);
            }
        }
        ,
        Country {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getCountry();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setCountry((String)value);
            }
        }
        ,
        CustMnjOntSoObinSizlineLINES {
            public Object get(CustMnjOntSoObinslineDetailImpl obj) {
                return obj.getCustMnjOntSoObinSizlineLINES();
            }

            public void put(CustMnjOntSoObinslineDetailImpl obj,
                            Object value) {
                obj.setCustMnjOntSoObinSizlineLINES((CustMnjOntSoObinSizlineLINESImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(CustMnjOntSoObinslineDetailImpl object);

        public abstract void put(CustMnjOntSoObinslineDetailImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SOOBINSLINEHID = AttributesEnum.SoObinslineHId.index();
    public static final int SALESORDERID = AttributesEnum.SalesOrderId.index();
    public static final int SOLINEID = AttributesEnum.SolineId.index();
    public static final int SOOBINSLINEID = AttributesEnum.SoObinslineId.index();
    public static final int ITEMCODE = AttributesEnum.ItemCode.index();
    public static final int SOOBNO = AttributesEnum.SoObno.index();
    public static final int SIZEGROUPID = AttributesEnum.SizeGroupId.index();
    public static final int INSEAMID = AttributesEnum.InseamId.index();
    public static final int TOTALRATIO = AttributesEnum.TotalRatio.index();
    public static final int INSEAMQTY = AttributesEnum.InseamQty.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int INVENTORYITEMID = AttributesEnum.InventoryItemId.index();
    public static final int OBREFNO = AttributesEnum.Obrefno.index();
    public static final int LEGACYID = AttributesEnum.LegacyId.index();
    public static final int PACKTYPE = AttributesEnum.PackType.index();
    public static final int UOM = AttributesEnum.Uom.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int LINENO = AttributesEnum.LineNo.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int SIZEVALUE = AttributesEnum.SizeValue.index();
    public static final int SIZEQTY = AttributesEnum.SizeQty.index();
    public static final int SIZEKEY = AttributesEnum.SizeKey.index();
    public static final int INSEAMSIZECONCAT = AttributesEnum.InseamSizeConcat.index();
    public static final int COUNTRY = AttributesEnum.Country.index();
    public static final int CUSTMNJONTSOOBINSIZLINELINES = AttributesEnum.CustMnjOntSoObinSizlineLINES.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CustMnjOntSoObinslineDetailImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.ont.model.entities.CustMnjOntSoObinslineDetail");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for SoObinslineHId, using the alias name SoObinslineHId.
     * @return the SoObinslineHId
     */
    public Number getSoObinslineHId() {
        return (Number)getAttributeInternal(SOOBINSLINEHID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SoObinslineHId.
     * @param value value to set the SoObinslineHId
     */
    public void setSoObinslineHId(Number value) {
        setAttributeInternal(SOOBINSLINEHID, value);
    }

    /**
     * Gets the attribute value for SalesOrderId, using the alias name SalesOrderId.
     * @return the SalesOrderId
     */
    public Number getSalesOrderId() {
        return (Number)getAttributeInternal(SALESORDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesOrderId.
     * @param value value to set the SalesOrderId
     */
    public void setSalesOrderId(Number value) {
        setAttributeInternal(SALESORDERID, value);
    }

    /**
     * Gets the attribute value for SolineId, using the alias name SolineId.
     * @return the SolineId
     */
    public Number getSolineId() {
        return (Number)getAttributeInternal(SOLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SolineId.
     * @param value value to set the SolineId
     */
    public void setSolineId(Number value) {
        setAttributeInternal(SOLINEID, value);
    }

    /**
     * Gets the attribute value for SoObinslineId, using the alias name SoObinslineId.
     * @return the SoObinslineId
     */
    public Number getSoObinslineId() {
        return (Number)getAttributeInternal(SOOBINSLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SoObinslineId.
     * @param value value to set the SoObinslineId
     */
    public void setSoObinslineId(Number value) {
        setAttributeInternal(SOOBINSLINEID, value);
    }

    /**
     * Gets the attribute value for ItemCode, using the alias name ItemCode.
     * @return the ItemCode
     */
    public String getItemCode() {
        return (String)getAttributeInternal(ITEMCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemCode.
     * @param value value to set the ItemCode
     */
    public void setItemCode(String value) {
        setAttributeInternal(ITEMCODE, value);
    }

    /**
     * Gets the attribute value for SoObno, using the alias name SoObno.
     * @return the SoObno
     */
    public String getSoObno() {
        return (String)getAttributeInternal(SOOBNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SoObno.
     * @param value value to set the SoObno
     */
    public void setSoObno(String value) {
        setAttributeInternal(SOOBNO, value);
    }

    /**
     * Gets the attribute value for SizeGroupId, using the alias name SizeGroupId.
     * @return the SizeGroupId
     */
    public String getSizeGroupId() {
        return (String)getAttributeInternal(SIZEGROUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizeGroupId.
     * @param value value to set the SizeGroupId
     */
    public void setSizeGroupId(String value) {
        setAttributeInternal(SIZEGROUPID, value);
    }

    /**
     * Gets the attribute value for InseamId, using the alias name InseamId.
     * @return the InseamId
     */
    public String getInseamId() {
        return (String)getAttributeInternal(INSEAMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InseamId.
     * @param value value to set the InseamId
     */
    public void setInseamId(String value) {
        setAttributeInternal(INSEAMID, value);
    }

    /**
     * Gets the attribute value for TotalRatio, using the alias name TotalRatio.
     * @return the TotalRatio
     */
    public Number getTotalRatio() {
        return (Number)getAttributeInternal(TOTALRATIO);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalRatio.
     * @param value value to set the TotalRatio
     */
    public void setTotalRatio(Number value) {
        setAttributeInternal(TOTALRATIO, value);
    }

    /**
     * Gets the attribute value for InseamQty, using the alias name InseamQty.
     * @return the InseamQty
     */
    public Number getInseamQty() {
        return (Number)getAttributeInternal(INSEAMQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for InseamQty.
     * @param value value to set the InseamQty
     */
    public void setInseamQty(Number value) {
        setAttributeInternal(INSEAMQTY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for InventoryItemId, using the alias name InventoryItemId.
     * @return the InventoryItemId
     */
    public Number getInventoryItemId() {
        return (Number)getAttributeInternal(INVENTORYITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InventoryItemId.
     * @param value value to set the InventoryItemId
     */
    public void setInventoryItemId(Number value) {
        setAttributeInternal(INVENTORYITEMID, value);
    }

    /**
     * Gets the attribute value for Obrefno, using the alias name Obrefno.
     * @return the Obrefno
     */
    public String getObrefno() {
        return (String)getAttributeInternal(OBREFNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Obrefno.
     * @param value value to set the Obrefno
     */
    public void setObrefno(String value) {
        setAttributeInternal(OBREFNO, value);
    }

    /**
     * Gets the attribute value for LegacyId, using the alias name LegacyId.
     * @return the LegacyId
     */
    public String getLegacyId() {
        return (String)getAttributeInternal(LEGACYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LegacyId.
     * @param value value to set the LegacyId
     */
    public void setLegacyId(String value) {
        setAttributeInternal(LEGACYID, value);
    }

    /**
     * Gets the attribute value for PackType, using the alias name PackType.
     * @return the PackType
     */
    public String getPackType() {
        return (String)getAttributeInternal(PACKTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PackType.
     * @param value value to set the PackType
     */
    public void setPackType(String value) {
        setAttributeInternal(PACKTYPE, value);
    }

    /**
     * Gets the attribute value for Uom, using the alias name Uom.
     * @return the Uom
     */
    public String getUom() {
        return (String)getAttributeInternal(UOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Uom.
     * @param value value to set the Uom
     */
    public void setUom(String value) {
        setAttributeInternal(UOM, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for LineNo, using the alias name LineNo.
     * @return the LineNo
     */
    public Number getLineNo() {
        return (Number)getAttributeInternal(LINENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineNo.
     * @param value value to set the LineNo
     */
    public void setLineNo(Number value) {
        setAttributeInternal(LINENO, value);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Attribute11, using the alias name Attribute11.
     * @return the Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute11.
     * @param value value to set the Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for Attribute12, using the alias name Attribute12.
     * @return the Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute12.
     * @param value value to set the Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for Attribute14, using the alias name Attribute14.
     * @return the Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute14.
     * @param value value to set the Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for Attribute15, using the alias name Attribute15.
     * @return the Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute15.
     * @param value value to set the Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for SizeValue, using the alias name SizeValue.
     * @return the SizeValue
     */
    public Number getSizeValue() {
        return (Number)getAttributeInternal(SIZEVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizeValue.
     * @param value value to set the SizeValue
     */
    public void setSizeValue(Number value) {
        setAttributeInternal(SIZEVALUE, value);
    }

    /**
     * Gets the attribute value for SizeQty, using the alias name SizeQty.
     * @return the SizeQty
     */
    public Number getSizeQty() {
        return (Number)getAttributeInternal(SIZEQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizeQty.
     * @param value value to set the SizeQty
     */
    public void setSizeQty(Number value) {
        setAttributeInternal(SIZEQTY, value);
    }

    /**
     * Gets the attribute value for SizeKey, using the alias name SizeKey.
     * @return the SizeKey
     */
    public String getSizeKey() {
        return (String)getAttributeInternal(SIZEKEY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizeKey.
     * @param value value to set the SizeKey
     */
    public void setSizeKey(String value) {
        setAttributeInternal(SIZEKEY, value);
    }

    /**
     * Gets the attribute value for InseamSizeConcat, using the alias name InseamSizeConcat.
     * @return the InseamSizeConcat
     */
    public String getInseamSizeConcat() {
        return (String)getAttributeInternal(INSEAMSIZECONCAT);
    }

    /**
     * Sets <code>value</code> as the attribute value for InseamSizeConcat.
     * @param value value to set the InseamSizeConcat
     */
    public void setInseamSizeConcat(String value) {
        setAttributeInternal(INSEAMSIZECONCAT, value);
    }

    /**
     * Gets the attribute value for Country, using the alias name Country.
     * @return the Country
     */
    public String getCountry() {
        return (String)getAttributeInternal(COUNTRY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Country.
     * @param value value to set the Country
     */
    public void setCountry(String value) {
        setAttributeInternal(COUNTRY, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity CustMnjOntSoObinSizlineLINESImpl.
     */
    public CustMnjOntSoObinSizlineLINESImpl getCustMnjOntSoObinSizlineLINES() {
        return (CustMnjOntSoObinSizlineLINESImpl)getAttributeInternal(CUSTMNJONTSOOBINSIZLINELINES);
    }

    /**
     * Sets <code>value</code> as the associated entity CustMnjOntSoObinSizlineLINESImpl.
     */
    public void setCustMnjOntSoObinSizlineLINES(CustMnjOntSoObinSizlineLINESImpl value) {
        setAttributeInternal(CUSTMNJONTSOOBINSIZLINELINES, value);
    }


    /**
     * @param soObinslineHId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number soObinslineHId) {
        return new Key(new Object[]{soObinslineHId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("CUST_MNJ_ONT_SO_OBINSLINE_S",getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setSoObinslineHId(sVal);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}
