package mnj.ont.model.entities;

import javax.faces.application.FacesMessage;

import javax.faces.context.FacesContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Feb 07 16:45:29 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustMnjOntSoObinSizlineLINESImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        SalesOrderId {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getSalesOrderId();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setSalesOrderId((Number)value);
            }
        }
        ,
        SolineId {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getSolineId();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setSolineId((Number)value);
            }
        }
        ,
        SoObinslineId {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getSoObinslineId();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setSoObinslineId((Number)value);
            }
        }
        ,
        SoObinsizlineId {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getSoObinsizlineId();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setSoObinsizlineId((Number)value);
            }
        }
        ,
        SizeGroupId {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getSizeGroupId();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setSizeGroupId((String)value);
            }
        }
        ,
        SizeId {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getSizeId();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setSizeId((String)value);
            }
        }
        ,
        Sizeratio {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getSizeratio();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setSizeratio((Number)value);
            }
        }
        ,
        SizeQty {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getSizeQty();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setSizeQty((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getCreationDate();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        Obrefno {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getObrefno();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setObrefno((String)value);
            }
        }
        ,
        Inseam {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getInseam();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setInseam((String)value);
            }
        }
        ,
        LegacyId {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getLegacyId();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setLegacyId((String)value);
            }
        }
        ,
        SizeLabel {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getSizeLabel();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setSizeLabel((String)value);
            }
        }
        ,
        LineCode {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getLineCode();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setLineCode((String)value);
            }
        }
        ,
        SizeSno {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getSizeSno();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setSizeSno((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getOrgId();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        OcNo {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getOcNo();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setOcNo((String)value);
            }
        }
        ,
        SizeP {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getSizeP();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setSizeP((Number)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getAttribute1();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getAttribute2();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getAttribute3();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getAttribute4();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getAttribute5();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getAttribute6();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getAttribute7();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getAttribute8();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getAttribute9();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getAttribute10();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getAttribute11();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getAttribute12();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getAttribute13();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getAttribute14();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getAttribute15();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        Uom {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getUom();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setUom((String)value);
            }
        }
        ,
        PackingType {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getPackingType();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setPackingType((String)value);
            }
        }
        ,
        InseamQty {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getInseamQty();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setInseamQty((Number)value);
            }
        }
        ,
        Country {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getCountry();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setCountry((String)value);
            }
        }
        ,
        ToDate {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getToDate();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setToDate((Date)value);
            }
        }
        ,
        CuttOff {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getCuttOff();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setCuttOff((String)value);
            }
        }
        ,
        DcpoNo {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getDcpoNo();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setDcpoNo((String)value);
            }
        }
        ,
        DeliveryDate {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getDeliveryDate();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setDeliveryDate((Date)value);
            }
        }
        ,
        DeliveryTerm {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getDeliveryTerm();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setDeliveryTerm((String)value);
            }
        }
        ,
        ShipMode {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getShipMode();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setShipMode((String)value);
            }
        }
        ,
        InventoryItemId {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getInventoryItemId();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setInventoryItemId((Number)value);
            }
        }
        ,
        DeliveryEndDate {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getDeliveryEndDate();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setDeliveryEndDate((Date)value);
            }
        }
        ,
        CustMnjOntSoObinslineDetail {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getCustMnjOntSoObinslineDetail();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        HeaderVO {
            public Object get(CustMnjOntSoObinSizlineLINESImpl obj) {
                return obj.getHeaderVO();
            }

            public void put(CustMnjOntSoObinSizlineLINESImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(CustMnjOntSoObinSizlineLINESImpl object);

        public abstract void put(CustMnjOntSoObinSizlineLINESImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SALESORDERID = AttributesEnum.SalesOrderId.index();
    public static final int SOLINEID = AttributesEnum.SolineId.index();
    public static final int SOOBINSLINEID = AttributesEnum.SoObinslineId.index();
    public static final int SOOBINSIZLINEID = AttributesEnum.SoObinsizlineId.index();
    public static final int SIZEGROUPID = AttributesEnum.SizeGroupId.index();
    public static final int SIZEID = AttributesEnum.SizeId.index();
    public static final int SIZERATIO = AttributesEnum.Sizeratio.index();
    public static final int SIZEQTY = AttributesEnum.SizeQty.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int OBREFNO = AttributesEnum.Obrefno.index();
    public static final int INSEAM = AttributesEnum.Inseam.index();
    public static final int LEGACYID = AttributesEnum.LegacyId.index();
    public static final int SIZELABEL = AttributesEnum.SizeLabel.index();
    public static final int LINECODE = AttributesEnum.LineCode.index();
    public static final int SIZESNO = AttributesEnum.SizeSno.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int OCNO = AttributesEnum.OcNo.index();
    public static final int SIZEP = AttributesEnum.SizeP.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int UOM = AttributesEnum.Uom.index();
    public static final int PACKINGTYPE = AttributesEnum.PackingType.index();
    public static final int INSEAMQTY = AttributesEnum.InseamQty.index();
    public static final int COUNTRY = AttributesEnum.Country.index();
    public static final int TODATE = AttributesEnum.ToDate.index();
    public static final int CUTTOFF = AttributesEnum.CuttOff.index();
    public static final int DCPONO = AttributesEnum.DcpoNo.index();
    public static final int DELIVERYDATE = AttributesEnum.DeliveryDate.index();
    public static final int DELIVERYTERM = AttributesEnum.DeliveryTerm.index();
    public static final int SHIPMODE = AttributesEnum.ShipMode.index();
    public static final int INVENTORYITEMID = AttributesEnum.InventoryItemId.index();
    public static final int DELIVERYENDDATE = AttributesEnum.DeliveryEndDate.index();
    public static final int CUSTMNJONTSOOBINSLINEDETAIL = AttributesEnum.CustMnjOntSoObinslineDetail.index();
    public static final int HEADERVO = AttributesEnum.HeaderVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CustMnjOntSoObinSizlineLINESImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.ont.model.entities.CustMnjOntSoObinSizlineLINES");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for SalesOrderId, using the alias name SalesOrderId.
     * @return the SalesOrderId
     */
    public Number getSalesOrderId() {
        return (Number)getAttributeInternal(SALESORDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesOrderId.
     * @param value value to set the SalesOrderId
     */
    public void setSalesOrderId(Number value) {
        setAttributeInternal(SALESORDERID, value);
    }

    /**
     * Gets the attribute value for SolineId, using the alias name SolineId.
     * @return the SolineId
     */
    public Number getSolineId() {
        return (Number)getAttributeInternal(SOLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SolineId.
     * @param value value to set the SolineId
     */
    public void setSolineId(Number value) {
        setAttributeInternal(SOLINEID, value);
    }

    /**
     * Gets the attribute value for SoObinslineId, using the alias name SoObinslineId.
     * @return the SoObinslineId
     */
    public Number getSoObinslineId() {
        return (Number)getAttributeInternal(SOOBINSLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SoObinslineId.
     * @param value value to set the SoObinslineId
     */
    public void setSoObinslineId(Number value) {
        setAttributeInternal(SOOBINSLINEID, value);
    }

    /**
     * Gets the attribute value for SoObinsizlineId, using the alias name SoObinsizlineId.
     * @return the SoObinsizlineId
     */
    public Number getSoObinsizlineId() {
        return (Number)getAttributeInternal(SOOBINSIZLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SoObinsizlineId.
     * @param value value to set the SoObinsizlineId
     */
    public void setSoObinsizlineId(Number value) {
        setAttributeInternal(SOOBINSIZLINEID, value);
    }

    /**
     * Gets the attribute value for SizeGroupId, using the alias name SizeGroupId.
     * @return the SizeGroupId
     */
    public String getSizeGroupId() {
        return (String)getAttributeInternal(SIZEGROUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizeGroupId.
     * @param value value to set the SizeGroupId
     */
    public void setSizeGroupId(String value) {
        setAttributeInternal(SIZEGROUPID, value);
    }

    /**
     * Gets the attribute value for SizeId, using the alias name SizeId.
     * @return the SizeId
     */
    public String getSizeId() {
        return (String)getAttributeInternal(SIZEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizeId.
     * @param value value to set the SizeId
     */
    public void setSizeId(String value) {
        setAttributeInternal(SIZEID, value);
    }

    /**
     * Gets the attribute value for Sizeratio, using the alias name Sizeratio.
     * @return the Sizeratio
     */
    public Number getSizeratio() {
        return (Number)getAttributeInternal(SIZERATIO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Sizeratio.
     * @param value value to set the Sizeratio
     */
    public void setSizeratio(Number value) {
        setAttributeInternal(SIZERATIO, value);
    }

    /**
     * Gets the attribute value for SizeQty, using the alias name SizeQty.
     * @return the SizeQty
     */
    public Number getSizeQty() {
        return (Number)getAttributeInternal(SIZEQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizeQty.
     * @param value value to set the SizeQty
     */
    public void setSizeQty(Number value) {
        setAttributeInternal(SIZEQTY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for Obrefno, using the alias name Obrefno.
     * @return the Obrefno
     */
    public String getObrefno() {
        return (String)getAttributeInternal(OBREFNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Obrefno.
     * @param value value to set the Obrefno
     */
    public void setObrefno(String value) {
        setAttributeInternal(OBREFNO, value);
    }

    /**
     * Gets the attribute value for Inseam, using the alias name Inseam.
     * @return the Inseam
     */
    public String getInseam() {
        return (String)getAttributeInternal(INSEAM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Inseam.
     * @param value value to set the Inseam
     */
    public void setInseam(String value) {
        setAttributeInternal(INSEAM, value);
    }

    /**
     * Gets the attribute value for LegacyId, using the alias name LegacyId.
     * @return the LegacyId
     */
    public String getLegacyId() {
        return (String)getAttributeInternal(LEGACYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LegacyId.
     * @param value value to set the LegacyId
     */
    public void setLegacyId(String value) {
        setAttributeInternal(LEGACYID, value);
    }

    /**
     * Gets the attribute value for SizeLabel, using the alias name SizeLabel.
     * @return the SizeLabel
     */
    public String getSizeLabel() {
        return (String)getAttributeInternal(SIZELABEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizeLabel.
     * @param value value to set the SizeLabel
     */
    public void setSizeLabel(String value) {
        setAttributeInternal(SIZELABEL, value);
    }

    /**
     * Gets the attribute value for LineCode, using the alias name LineCode.
     * @return the LineCode
     */
    public String getLineCode() {
        return (String)getAttributeInternal(LINECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineCode.
     * @param value value to set the LineCode
     */
    public void setLineCode(String value) {
        setAttributeInternal(LINECODE, value);
    }

    /**
     * Gets the attribute value for SizeSno, using the alias name SizeSno.
     * @return the SizeSno
     */
    public Number getSizeSno() {
        return (Number)getAttributeInternal(SIZESNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizeSno.
     * @param value value to set the SizeSno
     */
    public void setSizeSno(Number value) {
        setAttributeInternal(SIZESNO, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for OcNo, using the alias name OcNo.
     * @return the OcNo
     */
    public String getOcNo() {
        return (String)getAttributeInternal(OCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for OcNo.
     * @param value value to set the OcNo
     */
    public void setOcNo(String value) {
        setAttributeInternal(OCNO, value);
    }

    /**
     * Gets the attribute value for SizeP, using the alias name SizeP.
     * @return the SizeP
     */
    public Number getSizeP() {
        return (Number)getAttributeInternal(SIZEP);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizeP.
     * @param value value to set the SizeP
     */
    public void setSizeP(Number value) {
        setAttributeInternal(SIZEP, value);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Attribute11, using the alias name Attribute11.
     * @return the Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute11.
     * @param value value to set the Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for Attribute12, using the alias name Attribute12.
     * @return the Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute12.
     * @param value value to set the Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for Attribute14, using the alias name Attribute14.
     * @return the Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute14.
     * @param value value to set the Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for Attribute15, using the alias name Attribute15.
     * @return the Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute15.
     * @param value value to set the Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for Uom, using the alias name Uom.
     * @return the Uom
     */
    public String getUom() {
        return (String)getAttributeInternal(UOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Uom.
     * @param value value to set the Uom
     */
    public void setUom(String value) {
        setAttributeInternal(UOM, value);
    }

    /**
     * Gets the attribute value for PackingType, using the alias name PackingType.
     * @return the PackingType
     */
    public String getPackingType() {
        return (String)getAttributeInternal(PACKINGTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PackingType.
     * @param value value to set the PackingType
     */
    public void setPackingType(String value) {
        setAttributeInternal(PACKINGTYPE, value);
    }

    /**
     * Gets the attribute value for InseamQty, using the alias name InseamQty.
     * @return the InseamQty
     */
    public Number getInseamQty() {
        return (Number)getAttributeInternal(INSEAMQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for InseamQty.
     * @param value value to set the InseamQty
     */
    public void setInseamQty(Number value) {
        setAttributeInternal(INSEAMQTY, value);
    }

    /**
     * Gets the attribute value for Country, using the alias name Country.
     * @return the Country
     */
    public String getCountry() {
        return (String)getAttributeInternal(COUNTRY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Country.
     * @param value value to set the Country
     */
    public void setCountry(String value) {
        setAttributeInternal(COUNTRY, value);
    }

    /**
     * Gets the attribute value for ToDate, using the alias name ToDate.
     * @return the ToDate
     */
    public Date getToDate() {
        return (Date)getAttributeInternal(TODATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ToDate.
     * @param value value to set the ToDate
     */
    public void setToDate(Date value) {
        setAttributeInternal(TODATE, value);
    }

    /**
     * Gets the attribute value for CuttOff, using the alias name CuttOff.
     * @return the CuttOff
     */
    public String getCuttOff() {
        return (String)getAttributeInternal(CUTTOFF);
    }

    /**
     * Sets <code>value</code> as the attribute value for CuttOff.
     * @param value value to set the CuttOff
     */
    public void setCuttOff(String value) {
        setAttributeInternal(CUTTOFF, value);
    }

    /**
     * Gets the attribute value for DcpoNo, using the alias name DcpoNo.
     * @return the DcpoNo
     */
    public String getDcpoNo() {
        return (String)getAttributeInternal(DCPONO);
    }

    /**
     * Sets <code>value</code> as the attribute value for DcpoNo.
     * @param value value to set the DcpoNo
     */
    public void setDcpoNo(String value) {
        setAttributeInternal(DCPONO, value);
    }

    /**
     * Gets the attribute value for DeliveryDate, using the alias name DeliveryDate.
     * @return the DeliveryDate
     */
    public Date getDeliveryDate() {
        return (Date)getAttributeInternal(DELIVERYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliveryDate.
     * @param value value to set the DeliveryDate
     */
    public void setDeliveryDate(Date value) {
        setAttributeInternal(DELIVERYDATE, value);
    }

    /**
     * Gets the attribute value for DeliveryTerm, using the alias name DeliveryTerm.
     * @return the DeliveryTerm
     */
    public String getDeliveryTerm() {
        return (String)getAttributeInternal(DELIVERYTERM);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliveryTerm.
     * @param value value to set the DeliveryTerm
     */
    public void setDeliveryTerm(String value) {
        setAttributeInternal(DELIVERYTERM, value);
    }

    /**
     * Gets the attribute value for ShipMode, using the alias name ShipMode.
     * @return the ShipMode
     */
    public String getShipMode() {
        return (String)getAttributeInternal(SHIPMODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipMode.
     * @param value value to set the ShipMode
     */
    public void setShipMode(String value) {
        setAttributeInternal(SHIPMODE, value);
    }

    /**
     * Gets the attribute value for InventoryItemId, using the alias name InventoryItemId.
     * @return the InventoryItemId
     */
    public Number getInventoryItemId() {
        return (Number)getAttributeInternal(INVENTORYITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InventoryItemId.
     * @param value value to set the InventoryItemId
     */
    public void setInventoryItemId(Number value) {
        setAttributeInternal(INVENTORYITEMID, value);
    }

    /**
     * Gets the attribute value for DeliveryEndDate, using the alias name DeliveryEndDate.
     * @return the DeliveryEndDate
     */
    public Date getDeliveryEndDate() {
        return (Date)getAttributeInternal(DELIVERYENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliveryEndDate.
     * @param value value to set the DeliveryEndDate
     */
    public void setDeliveryEndDate(Date value) {
        setAttributeInternal(DELIVERYENDDATE, value);
    }


    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getCustMnjOntSoObinslineDetail() {
        return (RowIterator)getAttributeInternal(CUSTMNJONTSOOBINSLINEDETAIL);
    }

    /**
     * Uses the link HeaderLineVL to return rows of CustMnjOntSoObinSizlineLINESView
     */
    public ViewRowImpl getHeaderVO() {
        return (ViewRowImpl)getAttributeInternal(HEADERVO);
    }


    /**
     * @param soObinslineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number soObinslineId) {
        return new Key(new Object[]{soObinslineId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("CUST_MNJ_ONT_SO_OBIN_SIZLINE_S",getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setSoObinslineId(sVal);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        ViewObject vo = getDBTransaction().createViewObjectFromQueryStmt("select count(1) from CUST_MNJ_ONT_SO_OBINSLINE h where h.SO_OBINSLINE_ID ="+getSoObinslineId());
               vo.first();
               int count = 0 ;
               try{
                 count  =  Integer.parseInt(vo.getCurrentRow().getAttribute(0).toString());
               }catch(Exception e){
                   vo.remove();
               }
               if(count == 0 ){
                   super.remove();    
               }else
               {
                String messageText="Child Records exists , can't delete";
                  FacesMessage fm = new FacesMessage(messageText);          
                  fm.setSeverity(FacesMessage.SEVERITY_INFO);
                  FacesContext context = FacesContext.getCurrentInstance();
                  context.addMessage(null, fm);
                   
            }//end of else
            vo.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}
